apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: 3rax
data:
  PORT: "3001"
  NODE_ENV: "production"
  NATS_URL: "nats://192.168.50.118:4222"
  NATS_SUBJECT: "scanner.scans"
  # If PostgreSQL is running on the cluster:
  # DATABASE_URL: "postgresql://inventory:inventory@postgres-service:5432/inventory?schema=public"
  # If PostgreSQL is external:
  # DATABASE_URL: "postgresql://inventory:inventory@192.168.50.xxx:5432/inventory?schema=public"
